program: "train_and_visualize.py"
name: "DA6401_Assignment_3"
method: "bayes"
metric:
  goal: maximize
  name: validation_accuracy
parameters:
  epochs:
    values: [10,15]
  model_type:
    values: ["basic", "attention"]
  encoder_rnn_type:
    values: ["LSTM","GRU"]
  decoder_rnn_type:
    values: ["LSTM","GRU"]
  embedding_dim:
    values: [64,256]
  hidden_dim:
    values: [64,256]
  encoder_layers:
    values: [2,3]
  decoder_layers:
    values: [2,3]
  batch_size:
    values: [16, 32, 64]
  dropout:
    values: [0,0.2,0.3]
  learning_rate: 
    max: 0.001
    min: 0.0001
    distribution: log_uniform_values
  clip:
    values: [1.0, 2.0, 5.0]
  teacher_forcing_ratio:
    values: [0.5, 1.0]
  # decode_method:
  #   values: ["beam", "greedy"]
  # beam_width:
  #   values: [3,5]

  
  